### ISSUE TITLE
Dependencies between columns

### ISSUE THREAD

**Issue by chStaiger** [UtrechtUniversity/autumn-fair#3]
The data contains dependencies between columns, e.g. if an event takes place we expect an even ID, a time etc ...
Those need to be defined.

**Comment by lagerweijgr** [comment]
[Dependencies_AutumnFAIR.xlsx](https://github.com/user-attachments/files/16707022/Dependencies_AutumnFAIR.xlsx)
 
 Hereby the file, which I also upload in data folder.

**Comment by chStaiger** [comment]
Done
